concurrency:
  max: 5
  enable: false
  preemption:
    enable: false
    events:
    - mr_id
  exceed-action: IGNORE
sources:
  sciencediscovery:
    type: gitcode
    name: sciencediscovery
    branch: main
    git_url: https://gitcode.com/openJiuwen/sciencediscovery.git
    ssh_git_url: git@gitcode.com:openJiuwen/sciencediscovery.git
    endpoint_id: c4451a2a11af48baacd6b2af5eee3075
    repo_id: 10597680
on:
  sources:
    sciencediscovery:
      merge_requests:
        branches:
        - main
        paths: []
        types: []
        branches-ignore: []
        paths-ignore: []
        code-update: false
        merge_comment: /merge
stages:
  17876415983332873c1af-7bdb-4329-8424-4161cf516258:
    jobs:
      auto_merge:
        select: selected_by_default
        name: Merge the merge request with a rebase
        needs: []
        timeout: 20
        timeout_unit: minute
        steps:
        - name: Run the auto merge on the light image
          uses: official_devcloud_cloudBuild
          with:
            RUNNER_IMAGE: sciencediscovery-ci-light:latest
            GIT_REPO_URL: https://gitcode.com/openJiuwen/sciencediscovery.git
            GIT_REF: refs/heads/main
            GIT_TARGET_REF: refs/heads/main
            SH_FILE_PATH: .ci/codearts-auto-merge.sh
            ARTIFACT_PATH: .ci-results/auto-merge
            OBS_BUCKET: openjiuwen-ci
            OBS_DIRECTORY: "sciencediscovery/ci/auto-merge/${{ pipeline.run_id }}/"
            OBS_ENDPOINT: obs.cn-north-4.myhuaweicloud.com
            ENVS: |-
              CODEARTS_MERGE_ID=${MERGE_ID}
              CODEARTS_COMMIT_ID=${COMMIT_ID}
              GITCODE_TOKEN=${{ env.GITCODE_TOKEN }}
            STRICT_EXIT: "1"
            __sameProject__: "true"
            __projectId__: ""
            jobId: f0b81e4b4b554747b84171782f7a2b15
            __repository__: sciencediscovery
            artifactIdentifier: ""
          identifier: 1788756000000a1b2c3d4-7bdb-4329-8424-4161cf516258
        if: "${{ sources.sciencediscovery.merge_id != '' }}"
        runs-on:
        - default
    pre:
    - type: auto
    name: Auto merge
    select: selected_by_default
    fail-fast: false
